### ISSUE TITLE
Unable to render very simple components

### ISSUE THREAD

**Issue by kongweiying2** [fwouts/previewjs#1360]
### Describe the bug

Hey Francois!

I'm getting this error message on components that were previously working fine in past versions of Preview.js. After some investigation it seems like this happens on very simple components as well. 

```
Unable to render Bubble
While Preview.js can work out of the box for simple components, you may need a custom configuration to render components that depend on:

a specific state or context (see [Wrapping components](https://previewjs.com/docs/config/wrapper))
modules imported via [aliases](https://previewjs.com/docs/config/aliases)
[static assets](https://previewjs.com/docs/config/static-assets) or [SVGR](https://previewjs.com/docs/config/svgr)
Please see the logs below:

[14:50:10] Failed to resolve import "react/jsx-dev-runtime" from "react/jsx-dev-runtime". Does the file exist?

    at formatError (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
    at TransformContext.error (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
    at normalizeUrl (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39540:33)
    at async TransformContext.transform (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39673:47)
    at async Object.transform (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
    at async loadAndTransform (file:///Users/kongweiying/.vscode/extensions/zenclabs.previewjs-1.17.3/dist/node_modules/.pnpm/vite@4.0.4_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)
[Perhaps you need to install a peer dependency or configure aliases? See https://previewjs.com/docs/config/aliases](https://previewjs.com/docs/config/aliases)
[14:50:10] TypeError: Failed to fetch dynamically imported module: http://localhost:3140/preview/@component-loader.js?import&p=src%2Fview%2FBubble.tsx&c=Bubble
```

### Reproduction

1. Use this repro component

```
import React from 'react'

export const Bubble = (props: {}) => {
    return (
        <div>
            Lol
        </div>
    )
}
```
2. Click on the Preview.js hint above the component that shows

### Preview.js version

v1.17.3

### Framework

"react": "16.13.0", "react-dom": "16.13.0"

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 305.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
IDE:
    VSCode: 1.74.3
Browsers:
    Safari: 16.2


Also using Arc 0.85.0
```

### Used Package Manager

yarn

### Extension logs (useful for crashes)

```shell
Preview.js Server running at http://localhost:3140.
Failed to resolve dependency: react/jsx-runtime, present in 'optimizeDeps.include'
Failed to resolve dependency: react/jsx-dev-runtime, present in 'optimizeDeps.include'
Failed to resolve import "react/jsx-dev-runtime" from "2:38:24 PM [vite] Internal server error: Failed to resolve import "react/jsx-dev-runtime" from "Failed to resolve import "react/jsx-dev-runtime" from "Failed to resolve import "react/jsx-dev-runtime" from "2:38:24 PM [vite] ✨ new dependencies optimized: react-dom
2:38:24 PM [vite] ✨ optimized dependencies changed. reloading
Failed to resolve import "react/jsx-dev-runtime" from "2:38:25 PM [vite] Internal server error: Failed to resolve import "react/jsx-dev-runtime" from "Failed to resolve import "react/jsx-dev-runtime" from "Failed to resolve import "react/jsx-dev-runtime" from "Preview.js Server stopped.
```

### Repo link (if available)

Happy to share using VSCode Live Share or invite you to the repo, whichever is easiest for you.

**Comment by kongweiying2** [comment]
I ended up doing a search to see which version starts manifesting this error for me, by installing older versions of Preview.js. It looks like going from 1.15.3 -> 1.16.0. 1.15.3 works fine and then the same error starts showing from 1.16.0 onwards. Hope this helps!

**Comment by fwouts** [comment]
Hey @kongweiying2, sorry you're running into this. Have you tried updating to a more recent version of React 16, specifically 16.14.0?

**Comment by fwouts** [comment]
The reason why this broke is that Preview.js now uses the official Vite plugin for React, which relies on react/jsx-dev-runtime (introduced in v17 as well as v16.14.0). See https://github.com/vitejs/vite-plugin-react/blob/6756b854ce0e87cf5407139a4120994c3cd5df2c/packages/plugin-react/src/index.ts#L382 for the code.

Given React 16 is now ancient history, I will disable Preview.js for earlier versions than v16.14.0 :)

**Comment by kongweiying2** [comment]
Works perfectly in v16.14, too easy :)
