### ISSUE TITLE
PreviewJs not working in vscode

### ISSUE THREAD

**Issue by baditaflorin** [fwouts/previewjs#1392]
### Describe the bug

<img width="986" alt="image" src="https://user-images.githubusercontent.com/2330999/221860951-00790e4b-8a44-42e0-8104-828d2875d7e0.png">

### Reproduction

It was working ok until I installed vite-plugin-svgr 

Now, even if I removed the package and the node module folder, it still does not work anymore

### Preview.js version

v1.17.4

### Framework

React 18

### System Info

```shell
in macos M1 this does not complete, it remains frozen
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
2023-02-28 15:19:36.223 [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onLanguage:typescriptreact'

2023-02-28 15:19:59.019 [error] CodeWindow: failed to load (reason: ERR_CONNECTION_REFUSED, code: -102)

2023-02-28 15:07:23.354 [error] Unexpected token C in JSON at position 0: SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/index.js:2225:37)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

2023-02-28 15:13:24.998 [info] Getting Manifest... zenclabs.previewjs
2023-02-28 15:13:25.002 [info] Installing extension: zenclabs.previewjs
2023-02-28 15:13:26.196 [info] Extension signature verification: zenclabs.previewjs. Verification status: Verified.
2023-02-28 15:13:26.237 [info] Removed the extension from uninstalled list: zenclabs.previewjs
2023-02-28 15:13:26.255 [info] Extension installed successfully: zenclabs.previewjs
2023-02-28 15:13:33.267 [info] Getting Manifest... zenclabs.previewjs
2023-02-28 15:13:33.272 [info] Installing extension: zenclabs.previewjs
2023-02-28 15:13:33.459 [info] Extension installed successfully: zenclabs.previewjs
2023-02-28 15:19:24.171 [info] Worker process with pid 51468 terminated normally (type: fileWatcher, window: 8).
2023-02-28 15:19:28.929 [info] Starting worker process with pid 51741 (type: fileWatcher, window: 9).
2023-02-28 15:19:35.265 [info] Worker process with pid 51741 terminated normally (type: fileWatcher, window: 9).
2023-02-28 15:19:36.009 [info] Starting worker process with pid 51811 (type: fileWatcher, window: 9).
```

### Preview logs (useful for rendering errors)

```shell
I already removed the file vite-plugin-svgr and the preview.config.js file

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.readConfig (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+config@4.0.3/node_modules/@previewjs/config/dist/index.cjs:13:22)
    at /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:999:39
    at Previewer.startFromStopped (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:1047:9)
    at Previewer.start (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:986:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:914:15
500 in endpoint [object Object]:
frontend/preview.config.js:1
import svgr from 'vite-plugin-svgr'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.readConfig (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+config@4.0.3/node_modules/@previewjs/config/dist/index.cjs:13:22)
    at /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:999:39
    at Previewer.startFromStopped (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:1047:9)
    at Previewer.start (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:986:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:914:15
500 in endpoint [object Object]:
/frontend/preview.config.js:1
import svgr from 'vite-plugin-svgr'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.readConfig (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+config@4.0.3/node_modules/@previewjs/config/dist/index.cjs:13:22)
    at /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:999:39
    at Previewer.startFromStopped (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:1047:9)
    at Previewer.start (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:986:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:914:15
500 in endpoint [object Object]:
frontend/preview.config.js:1
import svgr from 'vite-plugin-svgr'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.readConfig (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+config@4.0.3/node_modules/@previewjs/config/dist/index.cjs:13:22)
    at /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:999:39
    at Previewer.startFromStopped (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:1047:9)
    at Previewer.start (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:986:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:914:15
✨ Created Preview.js workspace for: /frontend
500 in endpoint [object Object]:
frontend/preview.config.js:1
import svgr from 'vite-plugin-svgr'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1166:20)
    at Module._compile (node:internal/modules/cjs/loader:1210:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.readConfig (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+config@4.0.3/node_modules/@previewjs/config/dist/index.cjs:13:22)
    at /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:999:39
    at Previewer.startFromStopped (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:1047:9)
    at Previewer.start (/Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:986:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/florin/.vscode/extensions/zenclabs.previewjs-1.17.4/dist/node_modules/.pnpm/@previewjs+core@15.1.3_@types+node@18.14.0/node_modules/@previewjs/core/dist/index.cjs:914:15```


### Repo link (if available)

_No response_

### Anything else?

_No response_

**Comment by baditaflorin** [comment]
Uninstalling and reinstalling the extension did not work. 
Restarting VScode 10 times did not work
Killing node after deleting the file that I specified earlier did the job, as someone else suggested in another issue
```
killall node
```
 to make sure that Preview.js is definitely dead before you restart VS Code.

**Comment by baditaflorin** [comment]
And now I'm back to how I got to this mess in the first place
```
Unable to render TextDetails
While Preview.js can work out of the box for simple components, you may need a custom configuration to render components that depend on:

a specific state or context (see [Wrapping components](https://previewjs.com/docs/config/wrapper))
modules imported via [aliases](https://previewjs.com/docs/config/aliases)
[static assets](https://previewjs.com/docs/config/static-assets) or [SVGR](https://previewjs.com/docs/config/svgr)
Please see the logs below:

[15:31:32] SyntaxError: The requested module '/preview/src/Icons/LayersIcon.svg?import' does not provide an export named 'ReactComponent'
[Read https://previewjs.com/docs/config/svgr to configure SVGR for your project.](https://previewjs.com/docs/config/svgr)
```

**Comment by fwouts** [comment]
Hey @baditaflorin, thanks for the bug report and sorry Preview.js didn't behave as expected. It looks like using ESM inside the config file got it stuck badly and it wouldn't restart anymore like it's meant to 🙁

I'll look into it, thanks.

**Comment by fwouts** [comment]
Hey @baditaflorin, v1.19.3 has a bunch of error handling improvements (especially improving error visibility) that I'm hoping will help here.

It also supports ESM for preview.config.js if your package has `"type": "module"`, and shouldn't get into a stuck state anymore if there is an error evaluating the config file.

It should be available in a few minutes on the VS Code Marketplace. Let me know if it helps!

**Comment by baditaflorin** [comment]
Testing it now, and opened 2 new bug requests for some errors that have pop-up.
I can see that at least a function that did not work in the past is now working.

**Comment by fwouts** [comment]
Perfect, thank you @baditaflorin. For future reference to myself and others, the new issues are #1434 and #1435.

I'll close this one and give further updates on those, since they are more specific.
