### ISSUE TITLE
Failed to install dependencies because I'm using fish?

### ISSUE THREAD

**Issue by mallowigi** [fwouts/previewjs#140]
### Describe the bug

The plugin crashes at start because apparently I'm using fish or something like that

```
	React Preview failed to install dependencies.
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			
			java.lang.Error: Autojump is not installed. Please install it first from https://github.com/wting/autojump#installation
			plugin-node: npm is unavailable, either install it or set 
			in the config.fish file: set NPM_DIR /path/to/npm/dir
			fish: Unknown command: rbenv
			~/.local/share/omf/pkg/rbenv/init.fish (line 9): 
			if command rbenv init - | grep --quiet "function"
			^
			from sourcing file ~/.local/share/omf/pkg/rbenv/init.fish
...
```

### Reproduction

Just installed the plugin and restart WebStorm and the error occurred.

### Preview.js version

0.7.2

### System Info

```shell
java.lang.Error: Autojump is not installed. Please install it first from https://github.com/wting/autojump#installation plugin-node: npm is unavailable, either install it or set in the config.fish file: set NPM_DIR /path/to/npm/dir fish: Unknown command: rbenv ~/.local/share/omf/pkg/rbenv/init.fish (line 9): if command rbenv init - | grep --quiet "function" ^ from sourcing file ~/.local/share/omf/pkg/rbenv/init.fish called during startup in function 'require' with arguments '--path /Users/eliorboukhobza/.local/share/omf/pkg/autojump /Users/eliorboukhobza/.local/share/omf/pkg/balias /Users/eliorboukhobza/.local/share/omf/pkg/bass /Users/eliorboukhobza/.local/share/omf/pkg/brew /Users/eliorboukhobza/.local/share/omf/pkg/bundler /Users/eliorboukhobza/.local/share/omf/pkg/cd /Users/eliorboukhobza/.local/share/omf/pkg/extract /Users/eliorboukhobza/.local/share/omf/pkg/fish-spec /Users/eliorboukhobza/.local/share/omf/pkg/foreign-env /Users/eliorboukhobza/.local/share/omf/pkg/fzf /Users/eliorboukhobza/.local/share/omf/pkg/getopts /Users/eliorboukhobza/.local/share/omf/pkg/hash /Users/eliorboukhobza/.local/share/omf/pkg/kill-on-port /Users/eliorboukhobza/.local/share/omf/pkg/license /Users/eliorboukhobza/.local/share/omf/pkg/node /Users/eliorboukhobza/.local/share/omf/pkg/nvm /Users/eliorboukhobza/.local/share/omf/pkg/omf /Users/eliorboukhobza/.local/share/omf/pkg/osx /Users/eliorboukhobza/.local/share/omf/pkg/rails /Users/eliorboukhobza/.local/share/omf/pkg/rbenv /Users/eliorboukhobza/.local/share/omf/pkg/sublime /Users/eliorboukhobza/.local/share/omf/pkg/tab /Users/eliorboukhobza/.local/share/omf/pkg/technicolor /Users/eliorboukhobza/.local/share/omf/pkg/title /Users/eliorboukhobza/.local/share/omf/pkg/vcs /Users/eliorboukhobza/.local/share/omf/pkg/wifi-password' called on line 24 of file ~/.local/share/omf/init.fish from sourcing file ~/.local/share/omf/init.fish called on line 7 of file ~/.config/fish/conf.d/omf.fish from sourcing file ~/.config/fish/conf.d/omf.fish called on line 253 of file /usr/local/Cellar/fish/3.3.1/share/fish/config.fish from sourcing file /usr/local/Cellar/fish/3.3.1/share/fish/config.fish called during startup Please install 'brew' first! fish: Unknown command: il fish: il ^ at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService.install(ReactPreviewSharedService.kt:138) at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService.access$install(ReactPreviewSharedService.kt:25) at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService$actor$1.invokeSuspend(ReactPreviewSharedService.kt:56) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Used Package Manager

npm

**Comment by mallowigi** [comment]
duplicate

**Comment by mallowigi** [comment]
Reopened for visibility, plugin doesn't work because of that.

**Comment by mallowigi** [comment]
Maybe you need to support multiple shells through a settings of the sort.

**Comment by fwouts** [comment]
Hi @mallowigi, this should be fixed in Preview.js v1.6.0 (sorry it took so long). Would you mind trying it out? https://previewjs.com
