### ISSUE TITLE
Type alias name cannot be 'default'. (119:6)

### ISSUE THREAD

**Issue by baditaflorin** [fwouts/previewjs#1435]
### Describe the bug

At first, it shows for a few seconds this 
```
Unable to render aPlan
While Preview.js can work out of the box for simple components, you may need a custom configuration to render components that depend on:

a specific state or context (see [Wrapping components](https://previewjs.com/docs/config/wrapper))
modules imported via [aliases](https://previewjs.com/docs/config/aliases)
[static assets](https://previewjs.com/docs/config/static-assets) or [SVGR](https://previewjs.com/docs/config/svgr)
Please see the logs below:

[15:35:20.314] Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>
    at useLeafletContext (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-5XQIOF7E.js?v=6be07e9a:71:11)
    at usePath (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-5XQIOF7E.js?v=6be07e9a:354:21)
    at ContainerComponent (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-5XQIOF7E.js?v=6be07e9a:88:35)
    at renderWithHooks (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:12171:26)
    at updateForwardRef (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:14327:28)
    at beginWork (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:15934:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:3674:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:3699:24)
    at invokeGuardedCallback (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:3733:39)
    at beginWork$1 (http://localhost:3140/preview/node_modules/.previewjs/v18.0.1/vite/deps/chunk-TJIBBVYG.js?v=6be07e9a:19761:15)
```

and then it crashes and shows the 
```
The Preview.js client encountered a fatal error. This is most likely due to a bug in Preview.js itself and not in your code.

Please report the following in the [GitHub repo](https://github.com/fwouts/previewjs/issues):

Type alias name cannot be 'default'. (119:6)
  117 |             }
  118 |
> 119 | type default<T,> = {
      |      ^
  120 |               ["maxSize"]: number
  121 | ["insert"]: (...params: any[]) => (default<T>)
  122 | ["get"]: (...params: any[]) => (T | undefined)
SyntaxError: Type alias name cannot be 'default'. (119:6)
  117 |             }
  118 |
> 119 | type default<T,> = {
      |      ^
  120 |               ["maxSize"]: number
  121 | ["insert"]: (...params: any[]) => (default<T>)
  122 | ["get"]: (...params: any[]) => (T | undefined)
    at Fn (http://localhost:3140/assets/index-b3bf10d1.js:1196:25040)
    at Wd (http://localhost:3140/assets/index-b3bf10d1.js:1452:10991)
    at Object.fp [as parse] (http://localhost:3140/assets/index-b3bf10d1.js:1452:11316)
    at Object.Mr [as parse] (http://localhost:3140/assets/index-b3bf10d1.js:1120:1412)
    at On (http://localhost:3140/assets/index-b3bf10d1.js:1121:16386)
    at Ta (http://localhost:3140/assets/index-b3bf10d1.js:1125:643)
    at http://localhost:3140/assets/index-b3bf10d1.js:1196:7616
    at Object.format (http://localhost:3140/assets/index-b3bf10d1.js:1196:7708)
    at Sge (http://localhost:3140/assets/index-b3bf10d1.js:1454:82)
    at ysr (http://localhost:3140/assets/index-b3bf10d1.js:1538:3)
```

### Reproduction

Trying to open a default function in previewjs

### Preview.js version

1.9.23

### Framework

React 18

### System Info

```shell
MacOS M1
```

### Used Package Manager

npm

### Preview logs (useful for rendering errors)

```shell
Preview.js Server running at http://localhost:3140.
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
3  |  @tailwind utilities;
4  |  
5  |  @import url("https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap");
   |   ^
6  |  @import url("https://fonts.googleapis.com/css2?family=Montez&display=swap");
7  |  @import url("https://fonts.googleapis.com/css2?family=Eczar&subset=latin&effect=anaglyph&display=swap");
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
4  |  
5  |  @import url("https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap");
6  |  @import url("https://fonts.googleapis.com/css2?family=Montez&display=swap");
   |   ^
7  |  @import url("https://fonts.googleapis.com/css2?family=Eczar&subset=latin&effect=anaglyph&display=swap");
8  |  
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
5  |  @import url("https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap");
6  |  @import url("https://fonts.googleapis.com/css2?family=Montez&display=swap");
7  |  @import url("https://fonts.googleapis.com/css2?family=Eczar&subset=latin&effect=anaglyph&display=swap");
   |   ^
8  |  
9  |  * {
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(100%, 7) or calc(100% / 7)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
709 │       width: (100% / 7);
    │               ^^^^^^^^
    ╵
    src/react-google-flight-datepicker/lib/components/DatePicker/styles.scss 709:15  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(100%, 7) or calc(100% / 7)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
710 │       max-width: (100% / 7);
    │                   ^^^^^^^^
    ╵

From main, not sure if related
2023-03-10 15:19:07.223 [error] CodeWindow: failed to load (reason: <unknown>, code: -3)
```

### Anything else?

This is the start of the function I was trying to preview

export default function FunctionName({
  dispatch,
  aPlan,
  state,
}: {
  aPlan: PlanData;
  state: SomeState;
  dispatch: React.Dispatch<DispatchAction>;
}) [...]

**Comment by fwouts** [comment]
This is now shipped in v1.19.4, let me know if you see an improvement!
