### ISSUE TITLE
Preview.js does not work with { NavLink, Outlet } from "react-router-dom"

### ISSUE THREAD

**Issue by baditaflorin** [fwouts/previewjs#1466]
### Describe the bug

Trying to preview the pages using modern React Outlet method does not work in Preview.js

### Reproduction

I used the code from here https://github.com/iamshaunjp/react-router-in-depth/tree/lesson-4

### Preview.js version

latest

### Framework

React 18

### System Info

```shell
Macos
```

### Used Package Manager

npm

### Preview logs (useful for rendering errors)

```shell
Unable to render HelpLayout
While Preview.js can work out of the box for simple components, you may need a custom configuration to render components that depend on:

a specific state or context (see Wrapping components)
modules imported via aliases
static assets or SVGR
Please see the logs below:

[21:43:07.921] Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:197:11)
    at useLocation (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2868:34)
    at useResolvedPath (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2961:7)
    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3984:14)
    at renderWithHooks (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:12169:26)
    at updateForwardRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:14325:28)
    at beginWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:15932:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3672:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3697:24)
    at invokeGuardedCallback (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3731:39)
[21:43:07.922] Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:197:11)
    at useLocation (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2868:34)
    at useResolvedPath (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2961:7)
    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3984:14)
    at renderWithHooks (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:12169:26)
    at updateForwardRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:14325:28)
    at beginWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:15932:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3672:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3697:24)
    at invokeGuardedCallback (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3731:39)
[21:43:07.923] Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:197:11)
    at useLocation (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2868:34)
    at useResolvedPath (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2961:7)
    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3984:14)
    at renderWithHooks (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:12169:26)
    at updateForwardRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:14325:28)
    at beginWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:15932:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3672:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3697:24)
    at invokeGuardedCallback (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3731:39)
[21:43:07.923] Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:197:11)
    at useLocation (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2868:34)
    at useResolvedPath (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2961:7)
    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3984:14)
    at renderWithHooks (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:12169:26)
    at updateForwardRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:14325:28)
    at beginWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:15932:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3672:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3697:24)
    at invokeGuardedCallback (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:3731:39)
[21:43:07.925] The above error occurred in the <NavLink> component:

    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3976:21)
    at nav
    at div
    at HelpLayout
    at ErrorBoundary (http://localhost:3141/preview/@previewjs-virtual:/Users/florin/Documents/GITHUB_PROJECTS/react-router-in-depth/__previewjs_internal__/renderer/error-boundary.tsx:15:5)
    at Renderer

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
[21:43:07.925] The above error occurred in the <NavLink> component:

    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3976:21)
    at nav
    at div
    at HelpLayout
    at ErrorBoundary (http://localhost:3141/preview/@previewjs-virtual:/Users/florin/Documents/GITHUB_PROJECTS/react-router-in-depth/__previewjs_internal__/renderer/error-boundary.tsx:15:5)
    at Renderer

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
[21:43:08.016] Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:197:11)
    at useLocation (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2868:34)
    at useResolvedPath (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:2961:7)
    at NavLinkWithRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-router-dom.js?v=1c85fddc:3984:14)
    at renderWithHooks (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:12169:26)
    at updateForwardRef (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:14325:28)
    at beginWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:15932:22)
    at beginWork$1 (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:19747:22)
    at performUnitOfWork (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:19192:20)
    at workLoopSync (http://localhost:3141/preview/node_modules/.previewjs/v18.0.1/vite/deps/react-dom_client.js?v=1c85fddc:19131:13)
```

### Repo link (if available)

https://github.com/iamshaunjp/react-router-in-depth/tree/lesson-4

**Comment by fwouts** [comment]
Hey @baditaflorin, you will need to set up a wrapper component to make this work, see https://previewjs.com/docs/config/wrapper.

It might be as simple as [this example](https://github.com/fwouts/previewjs/blob/main/frameworks/react/tests/apps/cra-react-router/__previewjs__/Wrapper.tsx). Let me know if that works!
