### ISSUE TITLE
Can't get it working in Stackblitz

### ISSUE THREAD

**Issue by rudolfbyker** [fwouts/previewjs#2108]
### Describe the bug

The `previewjs` CLI works on my machine, but not in Stackblitz: https://stackblitz.com/edit/github-wnebwu

### Reproduction

1. Open https://stackblitz.com/edit/github-wnebwu
2. Run `previewjs` in the terminal
3. Observe error

### Preview.js CLI version

v1.25.3

### Framework

Nuxt 3.7.4

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### CLI logs (useful for crashes)

```shell
[09:14:50.828] FATAL (68): Unable to load @previewjs/core from /home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/node_modules/@previewjs/core/dist/index.mjs' imported from /home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js
    at makeNodeErrorWithCode/< (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:36:4174)
    at defaultResolve/y</< (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:114:12009)
    at defaultResolve/y< (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:114:12166)
    at defaultResolve (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:114:12174)
    at nextHookFactory/< (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:248:2120)
    at resolve (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:248:7565)
    at getModuleJob (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:248:4391)
    at import (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:248:4780)
    at importModuleDynamically (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:189:1425)
    at i.importModuleDynamicallyCallback (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:58:582)
    at _0x32a20f (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:355:351061)
    at importModule (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:20200:28)
    at loadModules (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:20188:28)
    at load2 (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:20231:64)
    at  (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:20834:27)
    at listener (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:17088:21)
    at _parseCommand/actionResult< (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:17778:69)
    at _chainOrCall (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:17692:16)
    at _parseCommand (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:17778:31)
    at parseAsync (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:17482:20)
    at  (/home/projects/jvmixpakw.github/node_modules/@previewjs/cli/dist/main.js:20849:9)
    at run (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:355:347178)
    at _evaluate (https://jvmixpakwgithub-on04.w-corp.staticblitz.com/blitz.7a1fe16d.js:355:352640) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Repo link (if available)

https://stackblitz.com/edit/github-wnebwu

**Comment by fwouts** [comment]
Thanks for the report @rudolfbyker.

When I try the StackBlitz link, it fails with a different error on the first run, which explains the error you get in subsequent runs:
```
❯ previewjs
[install:begin] Running pnpm install...
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +402
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 402, reused 0, downloaded 0, added 0
Progress: resolved 402, reused 0, downloaded 1, added 0
 EIO  EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26

pnpm: EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26
    at Error.fromJSON (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:87211)
    at Error.create (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:85656)
    at _0x4ea0c5.wbg.<computed> (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:141324)
    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[470]:0x598be
    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[91]:0xe12c
    at _0x417264 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:104460)
    at Module._0x3e2ae2 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:578311)
    at ce (file:///home/.pnpm/.pnpmfile.cjs:1:5849)
    at Object.eval [as importPackage] (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:81560:36)
    at eval (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:180500:65)
Error: Command failed with exit code 1: cd "/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/" && node pnpm/bin/pnpm.cjs install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +402
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 402, reused 0, downloaded 0, added 0
Progress: resolved 402, reused 0, downloaded 1, added 0
 EIO  EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26

pnpm: EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26
    at Error.fromJSON (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:87211)
    at Error.create (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:85656)
    at _0x4ea0c5.wbg.<computed> (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:141324)
    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[470]:0x598be
    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[91]:0xe12c
    at _0x417264 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:104460)
    at Module._0x3e2ae2 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:578311)
    at ce (file:///home/.pnpm/.pnpmfile.cjs:1:5849)
    at Object.eval [as importPackage] (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:81560:36)
    at eval (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:180500:65)
    at Error.fromJSON (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:87211)
    at Error.create (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:85656)
    at _0x4ea0c5.wbg.<computed> (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:141324)
    at _0x417264 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:104460)
    at Module._0x3e2ae2 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:578311)
    at ce (/home/.pnpm/.pnpmfile.cjs:1:5849)
    at Object.eval (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:81560:36)
    at eval (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:180500:65)
    at makeError (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:19126:13)
    at handlePromise (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:20049:29)
    at async loadModules (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:20185:5)
    at async load2 (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:20231:58)
    at async _Command.eval (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:20834:21)
    at async _Command.parseAsync (/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/main.js:17482:9) {
  shortMessage: 'Command failed with exit code 1: cd "/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/" && node pnpm/bin/pnpm.cjs install --frozen-lockfile',
  command: 'cd "/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/" && node pnpm/bin/pnpm.cjs install --frozen-lockfile',
  escapedCommand: 'cd "\\"/home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/\\"" "&&" node "pnpm/bin/pnpm.cjs" install --frozen-lockfile',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Lockfile is up to date, resolution step is skipped\n' +
    'Progress: resolved 1, reused 0, downloaded 0, added 0\n' +
    'Packages: +402\n' +
    '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n' +
    'Progress: resolved 402, reused 0, downloaded 0, added 0\n' +
    'Progress: resolved 402, reused 0, downloaded 1, added 0\n' +
    ' EIO  EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26\n' +
    '\n' +
    'pnpm: EIO: invalid type: map, expected an optionally borrowed string at line 1 column 26\n' +
    '    at Error.fromJSON (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:87211)\n' +
    '    at Error.create (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:85656)\n' +
    '    at _0x4ea0c5.wbg.<computed> (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:141324)\n' +
    '    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[470]:0x598be\n' +
    '    at https://w-credentialless.staticblitz.com/fs_bg.2a8baea5.wasm:wasm-function[91]:0xe12c\n' +
    '    at _0x417264 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:350:104460)\n' +
    '    at Module._0x3e2ae2 (https://githubwnebwu-cq30.w-credentialless.staticblitz.com/blitz.2a8baea5.js:355:578311)\n' +
    '    at ce (file:///home/.pnpm/.pnpmfile.cjs:1:5849)\n' +
    '    at Object.eval [as importPackage] (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:81560:36)\n' +
    '    at eval (file:///home/projects/github-wnebwu/node_modules/@previewjs/cli/dist/pnpm/dist/pnpm.cjs:180500:65)',
  stderr: '',
  cwd: '/home/projects/github-wnebwu',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

This feels like a StackBlitz issue, as it happens in `blitz.2a8baea5.js`.
