### ISSUE TITLE
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9120

### ISSUE THREAD

**Issue by tanghaochen** [fwouts/previewjs#284]
### Describe the bug

I reinstalled the IDE and plugins but it also didn't work.

### Reproduction

 I am not ideal.

### Preview.js version

0.7.2

### System Info

```shell
Bug 1
React Preview crashed
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			See detailed logs in C:\Users\Haochen Tang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\react-preview\control-plane\control-plane.log
			retrofit2.HttpException: HTTP 500 Internal Server Error
			at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
			at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
			at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
			at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
			at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
			at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
			at java.base/java.lang.Thread.run(Thread.java:829)


bug2
React Preview crashed
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			See detailed logs in C:\Users\Haochen Tang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\react-preview\control-plane\control-plane.log
			java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9120
			at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
			at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
			at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
			at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
			at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
			at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
			at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
			at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
			at okhttp3.inte... (show balloon)
```

### Used Package Manager

npm

### Preview.js logs (check bottom panel in IntelliJ)

```shell
Bug 1
React Preview crashed
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			See detailed logs in C:\Users\Haochen Tang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\react-preview\control-plane\control-plane.log
			retrofit2.HttpException: HTTP 500 Internal Server Error
			at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
			at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
			at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
			at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
			at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
			at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
			at java.base/java.lang.Thread.run(Thread.java:829)


bug2
React Preview crashed
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			See detailed logs in C:\Users\Haochen Tang\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\react-preview\control-plane\control-plane.log
			java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9120
			at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
			at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
			at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
			at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
			at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
			at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
			at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
			at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
			at okhttp3.inte... (show balloon)
```

**Comment by fwouts** [comment]
Hi @tanghaochen, could you try https://previewjs.com instead?
