### ISSUE TITLE
esbuild-darwin-64 missing (Apple Silicon)

### ISSUE THREAD

**Issue by ong-yinggao98** [fwouts/previewjs#51]
### Describe the bug

Attempting to preview an element causes React Preview to complain that `esbuild-darwin-64` is missing. However, the package is not compatible with Apple Silicon as it is for x64 not ARM64.

### Reproduction

1. Click on Open `React Element` in React Preview

### React Preview version

v0.7.1

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 159.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /opt/homebrew/bin/node
    npm: 7.24.0 - /opt/homebrew/bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.60.2 - /usr/local/bin/code
    Vim: 8.2 - /opt/homebrew/bin/vim
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 15.0
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
added 107 packages, and audited 108 packages in 14s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Bootstrapped successfully.
React Preview Server running at http://localhost:3140.
Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1642:15)
    at esbuildCommandAndArgs (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1698:11)
    at ensureServiceIsRunning (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1855:25)
    at Object.build (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1748:26)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:50679:54
    at Array.map (<anonymous>)
    at scanImports (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:50679:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async optimizeDeps (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:71133:30)
    at async runOptimize (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:74997:48)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3140
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.v.listen (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/635.js:2:246900)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:29647
    at new Promise (<anonymous>)
    at t.ReactPreviewServer.start (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:29601)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:27437
    at async t.Previewer.startFromStopped (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:27521)
    at async t.Previewer.start (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:26400)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3140
}
[Info  - 9:13:06 PM] Connection to server got closed. Server will restart.
Bootstrapped successfully.
React Preview Server running at http://localhost:3140.
Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1642:15)
    at esbuildCommandAndArgs (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1698:11)
    at ensureServiceIsRunning (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1855:25)
    at Object.build (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/esbuild/lib/main.js:1748:26)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:50679:54
    at Array.map (<anonymous>)
    at scanImports (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:50679:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async optimizeDeps (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:71133:30)
    at async runOptimize (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/vite/dist/node/chunks/dep-24231913.js:74997:48)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3140
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.v.listen (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/635.js:2:246900)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:29647
    at new Promise (<anonymous>)
    at t.ReactPreviewServer.start (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:29601)
    at /Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:27437
    at async t.Previewer.startFromStopped (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:27521)
    at async t.Previewer.start (/Users/admin/.vscode/extensions/zenclabs.reactpreview-0.7.1/dist/server/node_modules/@reactpreview/core/lib/index.js:1:26400)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3140
}
[Info  - 9:15:23 PM] Connection to server got closed. Server will restart.
Bootstrapped successfully.
React Preview Server running at http://localhost:3140.
```

**Comment by fwouts** [comment]
Thank you for trying this out, and sorry it didn't fix it for you!

Can you also confirm whether you're using the "Universal" or "Apple Silicon" version of VS Code?

**Comment by fwouts** [comment]
I wouldn't say that's your mistake, ideally React Preview would work either way (in fact that was the case before esbuild started using optional dependencies). I'll keep this bug open so others find the solution more easily and I'll see if I can at least make the error more helpful.

**Comment by keithkraker** [comment]
Yeah, no problem.

VS Code: 1.61.1
Node: 14.18.0
NPM: 7.24.1
