### ISSUE TITLE
Frequent `Error: Cannot update an unmounted root.` when swapping between components in the same code file

### ISSUE THREAD

**Issue by katharosada** [fwouts/previewjs#518]
### Describe the bug

When I am working on two components in the same file, I get errors when trying to load a different component in the same JS file into Preview.js.

Whichever component I clicked first will work, it will load the preview correctly. The order in the file doesn't seem to matter. But if I try to load a different component once any component is already loaded, it gives me this error. Trying again, doesn't resolve it, loading a different component (other than the failed one) will work and if you have three components in the same file then you can cycle between them and load all of them except every second switch will fail.

Loading any component from a different file works, it seems to only be switching between components in the same file.

Here's the full error:
```
Error: Cannot update an unmounted root.
    at ReactDOMRoot.ReactDOMHydrationRoot.render.ReactDOMRoot.render (http://localhost:3140/preview/node_modules/.previewjs/v3.1.0/vite/deps/chunk-CIMS5AGV.js?v=54a97522:20166:19)
    at render (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/render-18?import:22:8)
    at render (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/index.tsx:38:13)
    at async updateComponent (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/update-component.ts:66:5)
    ```

### Reproduction

1. Create a new React project with `create-react-app`
2. Create a new code file `Foo.js` with the following contents:

```js
function FooBar() {
  return <p>FooBar</p>
}

function Foo() {
  return <p>Foo</p>
}
```

3. Click the little `Open FooBar in Preview.js` link above `FooBar` (it loads correctly)
4. Now click the little `Open Foo in Preview.js` link above `Foo` (observe error)

A red error appears below the Preview.js window as described above.

### Preview.js version

v1.6.4

### System Info

```shell
Mac M1, VSCode Version: 1.66.2 (Universal)
```

### Used Package Manager

yarn

### Preview logs (useful for rendering errors)

```shell
Cannot repro when opening in browser.
```

**Comment by fwouts** [comment]
Thanks for the bug report! Found the source of the bug, fix coming up soon :)

**Comment by fwouts** [comment]
The fix is now available in the VS Code extension (v.1.7.0) and pending review for JetBrains. Let me know if you see any issues!
