### ISSUE TITLE
Red `ErrorBoundary` messages in the console remain after error is resolved

### ISSUE THREAD

**Issue by katharosada** [fwouts/previewjs#519]
### Describe the bug

When editing a component while the preview pane is open - understandably the code is in an intermediate state when actively typing and will often be invalid code or throw errors.

When the error is resolved (code has been fixed) there are error messages in the console still. They don't seem to be the error themselves, but a residual error message hangs around.

Expected behaviour: The console is cleared when a new version of the component is loaded, and only shows errors and console messages from the latest version of the component code.

```
[19:30:09] The above error occurred in the <FooBar> component:

    at FooBar (http://localhost:3140/preview/src/Immutability/Example.js?import&t=1651311009212:2:3)
    at Renderer
    at ErrorBoundary (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/ErrorBoundary.tsx:9:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
[19:30:09] The above error occurred in the <FooBar> component:

    at FooBar (http://localhost:3140/preview/src/Immutability/Example.js?import&t=1651311009297:2:3)
    at Renderer
    at ErrorBoundary (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/ErrorBoundary.tsx:9:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
[19:30:09] The above error occurred in the <FooBar> component:

    at FooBar (http://localhost:3140/preview/src/Immutability/Example.js?import&t=1651311009361:2:3)
    at Renderer
    at ErrorBoundary (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/ErrorBoundary.tsx:9:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
[19:30:09] The above error occurred in the <FooBar> component:

    at FooBar (http://localhost:3140/preview/src/Immutability/Example.js?import&t=1651311009416:2:3)
    at Renderer
    at ErrorBoundary (http://localhost:3140/preview/@previewjs-virtual:/Users/katie/Projects/general-assembly/react-course/testing-ground/my-app/__previewjs_internal__/renderer/ErrorBoundary.tsx:9:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Reproduction

1. Create a new project with `create-react-app`
2. Add a component `FooBar`

```js
function FooBar() {
  return <p>FooBar</p>
}
```

Click 'open FooBar in preview.js` to open the preview in a separate VSCode panel

Edit the code to look like this (by typing, not by copy paste, it must go through invalid states).
```js
function FooBar() {
  const foo = 'hi'
  return <p>FooBar</p>
}
```

Observe that errors are coming up the Console panel of the Preview - and they remain even after the code has reached a valid state.

### Preview.js version

v1.6.4

### System Info

```shell
Mac M1, VSCode Version: 1.66.2 (Universal)
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Awesome repro instructions 👍 That should be fixable, I'll make sure to add some regression tests as well.

**Comment by fwouts** [comment]
The fix is now available in the VS Code extension (v.1.7.0) and pending review for JetBrains. Let me know if you see any issues!
