### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by SimeonC** [fwouts/previewjs#53]
### Describe the bug

Recieved this error message in the event log.

```
2021/10/07
10:39	React Preview failed to install dependencies.
			Please report this issue at https://github.com/zenclabs/reactpreview/issues
			
			java.lang.Error: Please install 'brew' first!
			TERM environment variable not set.
			TERM environment variable not set.
			fish: Unknown command: il
			fish: 
			il
			^
			at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService.install(ReactPreviewSharedService.kt:138)
			at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService.access$install(ReactPreviewSharedService.kt:25)
			at com.reactpreview.intellij.plugin.services.ReactPreviewSharedService$actor$1.invokeSuspend(ReactPreviewSharedService.kt:56)
			at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
			at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
			at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
			at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
			at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
			at kotlinx.coroutines.scheduling.Coroutin... (show balloon)
```

### Reproduction

I assume this has to do with my usage of fishshell so the install script cannot find homebrew, I have homebrew correctly installed and use it regularly.

### React Preview version

0.7.0

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 73.63 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.4.2 - ~/.asdf/installs/nodejs/16.4.2/bin/node
    npm: 7.21.0 - ~/Development/settings-frontend/node_modules/.bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 94.0.4606.71
    Firefox: 91.0.2
    Safari: 15.0
```

### Used Package Manager

npm

### Anything else?

I think this can probably be fixed by telling the install script to use `/bin/sh` or similar rather than using whatever the user has installed on their system as a default shell.

**Comment by fwouts** [comment]
Hi @SimeonC, this should be fixed in Preview.js v1.6.0 (sorry it took so long). Would you mind trying it out? https://previewjs.com
